blank_issues_enabled: true
contact_links:
  - name: Creative official support
    url: https://support.creative.com/Products/ProductDetails.aspx?catID=4&prodID=24120&subCatID=848
    about: Contact Creative for official product and warranty support.
